//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_vr_interaction : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single Movement
        {
            get
            {
                return SteamVR_Actions.vr_interaction_Movement;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.vr_interaction_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean EndTrial
        {
            get
            {
                return SteamVR_Actions.vr_interaction_EndTrial;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.vr_interaction_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadUp
        {
            get
            {
                return SteamVR_Actions.vr_interaction_TrackpadUp;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadDown
        {
            get
            {
                return SteamVR_Actions.vr_interaction_TrackpadDown;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadLeft
        {
            get
            {
                return SteamVR_Actions.vr_interaction_TrackpadLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean TrackpadRight
        {
            get
            {
                return SteamVR_Actions.vr_interaction_TrackpadRight;
            }
        }
    }
}
